name: ls-having
summary: List directories having specified flag files and meeting other conditions. 
description: |
  This is a tool that can list directories having specified flag files and optionally meeting other specified conditions.
  It is handy for developers maintaining mono repos that have multiple projects in each repo,
  and also suitable for CI/CD use cases.
  It is quick and small. Pre-built binaries are available for Linux, MacOS, and Windows.
version: git
grade: stable
base: core20

confinement: strict

apps:
  ls-having:
    command: bin/ls-having
    plugs:
      - home
parts:
  ls-having:
    plugin: go
    source-type: local
    source: .