name: CI

on:
  push:
    branches: [ master, main, develop, feature/**, chore/**, bugfix/**, hotfix/**, misc/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true
      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic -coverpkg=github.com/handy-common-utils/ls-having/lsh,github.com/handy-common-utils/ls-having
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3