name: Release

on:
  push:
    # run only against version tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9a-zA-Z.-]+'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true
      - run: go build
      - run: go test
  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/goreleaser/goreleaser/issues/1715#issuecomment-667002748
      - run: |
          sudo snap install --classic snapcraft
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_PAT }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
  publish-go-module:
    needs: [goreleaser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true
      - run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          GOPROXY=proxy.golang.org go list -m "github.com/handy-common-utils/ls-having@$TAG"
          curl -s "https://proxy.golang.org/github.com/handy-common-utils/ls-having/@v/$TAG.info"